<a href="https://colab.research.google.com/github/mr-alamdari/NLP-Topic-Modeling/blob/main/NLP_Topic_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import nltk
import pandas as pd
from sklearn import feature_extraction, decomposition

In [5]:
!wget https://raw.githubusercontent.com/mr-alamdari/NLP-Topic-Modeling/main/npr.zip

--2022-04-30 07:49:59--  https://raw.githubusercontent.com/mr-alamdari/NLP-Topic-Modeling/main/npr.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20982000 (20M) [application/zip]
Saving to: ‘npr.zip’

npr.zip             100%[===================>]  20.01M  --.-KB/s    in 0.1s    

2022-04-30 07:50:00 (148 MB/s) - ‘npr.zip’ saved [20982000/20982000]



In [10]:
!unzip npr.zip

Archive:  npr.zip
  inflating: npr.csv                 


In [11]:
npr = pd.read_csv('npr.csv')

In [12]:
npr.tail()

Article
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

In [13]:
npr.Article[34]

'U. S. Supreme Court Chief Justice John Roberts praised the   work of federal district judges in his   report on the federal judiciary, avoiding any talk of politics in regards to the country’s judicial system. Incoming president Donald Trump will have more than a 100 vacancies to fill at the district and appellate court level nationwide. He’ll also be able to fill the Supreme Court seat vacated following the death of Justice Antonin Scalia. The   Congress has refused to hold a hearing on President Obama’s nominee for that empty seat. The future of those judicial vacancies was a key issue in the presidential election. Roberts’ focus, however, was on the work of lower court judges, who he called ”selfless, patriotic and brave individuals.” Congress has authorized 637 district court judgeships across the country. And the people working in those positions do so largely out of the public eye, Roberts wrote. ”You might be asking at this point why any lawyer would want a job that requires lo

In [14]:
len(npr.Article[34])

2315

In [20]:
#max_df ==> discard words that show up in more than 90% of all the sentences
#min_df ==> discard words that show up in less than 9% of all the sentences(freq count=4)

cv = feature_extraction.text.CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [21]:
dtm = cv.fit_transform(npr.Article)

In [22]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [23]:
dtm.shape

(11992, 54777)

In [26]:
LDA = decomposition.LatentDirichletAllocation(n_components=7, random_state=32)

In [27]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=32)

In [28]:
len(cv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [34]:
cv.get_feature_names()[5000:5020]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['bask',
 'basked',
 'baskerville',
 'baskervilles',
 'basket',
 'basketball',
 'basketballs',
 'baskets',
 'basking',
 'basmati',
 'basquiat',
 'basra',
 'bass',
 'bassam',
 'bassett',
 'bassinet',
 'bassinets',
 'bassist',
 'bassists',
 'bassline']

####Grap Topics

In [37]:
len(LDA.components_)

7

In [38]:
LDA.components_.shape

(7, 54777)

In [39]:
LDA.components_[0]

array([2.89075182e+00, 2.58247675e+03, 1.42866015e-01, ...,
       1.43087138e-01, 1.42859954e-01, 1.42859389e-01])

In [40]:
single_topic = LDA.components_[0]

In [47]:
single_topic.argsort()[-10:]

array([32089, 46581, 54403, 33390, 42561,  8149, 36310, 36283, 22673,
       42993])

In [59]:
n=10
top_words_id = single_topic.argsort()[-n:]
top_words = [cv.get_feature_names()[i] for i in top_words_id]
top_words

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['money',
 'state',
 'year',
 'new',
 'said',
 'care',
 'percent',
 'people',
 'health',
 'says']

In [60]:
n=20
top_words_id = single_topic.argsort()[-n:]
top_words = [cv.get_feature_names()[i] for i in top_words_id]
top_words

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['company',
 'program',
 'public',
 'states',
 'companies',
 'school',
 'years',
 'federal',
 '000',
 'million',
 'money',
 'state',
 'year',
 'new',
 'said',
 'care',
 'percent',
 'people',
 'health',
 'says']

In [61]:
n=30
top_words_id = single_topic.argsort()[-n:]
top_words = [cv.get_feature_names()[i] for i in top_words_id]
top_words

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['work',
 'don',
 'tax',
 'pay',
 'make',
 'government',
 'students',
 'insurance',
 'just',
 'like',
 'company',
 'program',
 'public',
 'states',
 'companies',
 'school',
 'years',
 'federal',
 '000',
 'million',
 'money',
 'state',
 'year',
 'new',
 'said',
 'care',
 'percent',
 'people',
 'health',
 'says']

####Grap the highest probability words per Topics


In [65]:
for index, topic in enumerate(LDA.components_):
  n=20
  print(index)
  top_words_id = topic.argsort()[-n:]
  top_words = [cv.get_feature_names()[i] for i in top_words_id]
  print(top_words, end='\n\n')

0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['company', 'program', 'public', 'states', 'companies', 'school', 'years', 'federal', '000', 'million', 'money', 'state', 'year', 'new', 'said', 'care', 'percent', 'people', 'health', 'says']

1
['presidential', 'voters', 'country', 'vote', 'donald', 'party', 'people', 'political', 'republican', 'white', 'election', 'new', 'state', 'house', 'obama', 'campaign', 'clinton', 'president', 'said', 'trump']

2
['like', 'risk', 'blood', 'medical', 'human', 'said', 'virus', 'years', 'research', 'researchers', 'university', 'scientists', 'zika', 'patients', 'new', 'health', 'study', 'disease', 'people', 'says']

3
['say', 'school', 'make', 'want', 'lot', 've', 'things', 'going', 'life', 'women', 'way', 'don', 'time', 'really', 'know', 'think', 'just', 'people', 'like', 'says']

4
['small', 'land', 'country', 'make', '000', 'home', 'time', 'year', 'war', 'water', 'day', 'city', 'just', 'world', 'years', 'new', 'people', 'like', 'food', 'says']

5
['npr', 'game', 'love', 'best', 'songs', 'band', 

####Categorize each sentence to it's topic by their probability for each topic
###LDA

In [66]:
topic_results = LDA.transform(dtm)

In [74]:
topic_results[-20:].round(2)

array([[0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.  , 0.12, 0.  , 0.79, 0.08],
       [0.13, 0.09, 0.04, 0.14, 0.21, 0.12, 0.26],
       [0.  , 0.  , 0.  , 0.36, 0.  , 0.53, 0.11],
       [0.01, 0.  , 0.03, 0.24, 0.56, 0.04, 0.12],
       [0.  , 0.35, 0.  , 0.22, 0.  , 0.42, 0.01],
       [0.03, 0.  , 0.06, 0.91, 0.  , 0.  , 0.  ],
       [0.12, 0.12, 0.  , 0.  , 0.29, 0.34, 0.13],
       [0.09, 0.05, 0.  , 0.24, 0.  , 0.  , 0.61],
       [0.06, 0.36, 0.05, 0.07, 0.42, 0.  , 0.03],
       [0.06, 0.46, 0.  , 0.  , 0.  , 0.  , 0.47],
       [0.02, 0.01, 0.21, 0.  , 0.  , 0.  , 0.76],
       [0.37, 0.  , 0.45, 0.11, 0.  , 0.02, 0.05],
       [0.  , 0.  , 0.  , 0.24, 0.74, 0.02, 0.  ],
       [0.07, 0.  , 0.56, 0.  , 0.37, 0.  , 0.  ],
       [0.27, 0.  , 0.  , 0.  , 0.  , 0.  , 0.73],
       [0.  , 0.7 , 0.  , 0.06, 0.  , 0.23, 0.  ],
       [0.  , 0.04, 0.5 , 0.24, 0.06, 0.  , 0.16],
       [0.01, 0.87, 0.  , 0.12, 0.  , 0.  , 0.  ],
       [0.17, 0.3 , 0.  , 0.07,

In [76]:
topic_results.shape

(11992, 7)

In [84]:
npr['Topic'] = topic_results.argmax(axis=1)

In [86]:
npr.tail()

Article  Topic
11987  The number of law enforcement officers shot an...      6
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      2
11990  The election of Donald Trump was a surprise to...      1
11991  Voters in the English city of Sunderland did s...      4

###Non-Negative Matrix Factorization
######An unsupervise algorithm that simultaneously performs dimensionality reduction and clustering

####Categorize each sentence to it's topic by their coefficient for each topic
###NMF

In [91]:
npr = pd.read_csv('npr.csv')

In [93]:
tfidf = feature_extraction.text.TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [94]:
dtm = tfidf.fit_transform(npr.Article)

In [95]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [96]:
dtm.shape

(11992, 54777)

In [97]:
nmf_model = decomposition.NMF(n_components=7, random_state=32)

In [98]:
nmf_model.fit(dtm)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


NMF(n_components=7, random_state=32)

In [103]:
tfidf.get_feature_names()[233]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'1848'

In [104]:
for index, topic in enumerate(nmf_model.components_):
  n=20
  print(index)
  top_words_id = topic.argsort()[-n:]
  top_words = [cv.get_feature_names()[i] for i in top_words_id]
  print(top_words, end='\n\n')

0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['years', 'brain', 'university', 'researchers', 'scientists', 'new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']

1
['intelligence', 'office', 'nominee', 'republicans', 'comey', 'gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']

2
['insurers', 'federal', 'said', 'aca', 'repeal', 'senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']

3
['killed', 'reported', 'military', 'justice', 'city', 'officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']

4
['candidate', 'said', 'win', 'candidates', 'republican', 'primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 's

In [106]:
topic_results =nmf_model.transform(dtm)

In [110]:
topic_results[2].round(2)

array([0.  , 0.14, 0.  , 0.04, 0.02, 0.  , 0.  ])

In [111]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [112]:
npr['Topic'] = topic_results.argmax(axis=1)

In [113]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      3
4      From photography, illustration and video, to d...      6
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      3
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      0
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      3

[11992 rows x 2 columns]

In [114]:
topic_names = {0:'study',
               1:'election',
               2:'politic',
               3:'politic',
               4:'election',
               5:'music',
               6:'Study'}

In [118]:
npr['Topic'] = npr['Topic'].map(topic_names)

In [119]:
npr

Article     Topic
0      In the Washington of 2016, even when the polic...  election
1        Donald Trump has used Twitter  —   his prefe...  election
2        Donald Trump is unabashedly praising Russian...  election
3      Updated at 2:50 p. m. ET, Russian President Vl...   politic
4      From photography, illustration and video, to d...     Study
...                                                  ...       ...
11987  The number of law enforcement officers shot an...   politic
11988    Trump is busy these days with victory tours,...  election
11989  It’s always interesting for the Goats and Soda...     study
11990  The election of Donald Trump was a surprise to...  election
11991  Voters in the English city of Sunderland did s...   politic

[11992 rows x 2 columns]