<a href="https://colab.research.google.com/github/mr-alamdari/NLP-Classification-and-Vector-Spaces-Begginer/blob/main/NLP_Classification_and_Vector_Spaces_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#1.Data

##[Large Movie Review Dataset](https://ai.stanford.edu/~amaas/data/sentiment/)

In [4]:
!wget https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz

--2022-04-13 11:36:46--  https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
Resolving ai.stanford.edu (ai.stanford.edu)... 171.64.68.10
Connecting to ai.stanford.edu (ai.stanford.edu)|171.64.68.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84125825 (80M) [application/x-gzip]
Saving to: ‘aclImdb_v1.tar.gz’

aclImdb_v1.tar.gz   100%[===================>]  80.23M  23.5MB/s    in 4.0s    

2022-04-13 11:36:50 (19.9 MB/s) - ‘aclImdb_v1.tar.gz’ saved [84125825/84125825]



In [5]:
import tarfile
files = tarfile.open('/content/aclImdb_v1.tar.gz')
files.extractall('/content/')

In [6]:
path2data = '/content/aclImdb/'

os.listdir(path2data)

['imdbEr.txt', 'imdb.vocab', 'train', 'test', 'README']

In [7]:
path2datasets = []
path2train = []

for root, dirs, files in os.walk(path2data):
  if 'pos' in root or 'neg' in root:
    print(root, len(files))
    path2datasets.append(root)


/content/aclImdb/train/neg 12500
/content/aclImdb/train/pos 12500
/content/aclImdb/test/neg 12500
/content/aclImdb/test/pos 12500


So we have 12500 number of comments on each pos or neg folder.
but we are going to use 4 of them to start our practice

In [8]:
data_dic = {}
for ds in path2datasets:

  temp_arr = []
  for c_path in os.listdir(ds):

    path = f'{ds}/{c_path}'
    with open (path, 'r') as f:
      temp_arr.append(f.read())
  
  data_dic[f"{ds.replace('/content/aclImdb/', '').replace('/', '_')}"] = temp_arr

In [9]:
data_df = pd.DataFrame(data_dic)

In [10]:
data_df

train_neg  \
0      Well, what are the odds! At the exact right mo...   
1      Director F.W. Murnau wisely stuck with the sil...   
2      I desperately want to give this movie a 10...I...   
3      I can't imagine anyone would ever, in a millio...   
4      Awful! Awful! Awful! No, I didn't like it. It ...   
...                                                  ...   
12495  This stalk and slash turkey manages to bring n...   
12496  This has to be THE WORST film I have ever seen...   
12497  Prom Night is about a girl named Donna (Britta...   
12498  My boyfriend and I rented this because we thou...   
12499  The Fluffer may have strong elements of porn i...   

                                               train_pos  \
0      For persons of a certain age, W.W. II was the ...   
1      I hated the first episode of this show ( 'Prot...   
2      Eddie Izzard is nothing short of a comedic gen...   
3      This is a comedy based on national stereotypes...   
4      If Jean Renoir's first film "Whirlpool of Fate...   
...                                                  ...   
12495  What another reviewer called lack of character...   
12496  Most reviews say that this is the weakest poin...   
12497  I always enjoy this movie when it shows up on ...   
12498  As a 90 minute experience, it is not up to the...   
12499  This is the best version (so far) that you wil...   

                                                test_neg  \
0      If it would of had Jack Black listed as the le...   
1      The Quick and the Undead is, finally, the firs...   
2      Like many others, I counted on the appearance ...   
3      I enjoyed Carax's "Les Amants du Pont Neuf" an...   
4      If this film won the Lumiere Award for Best Fr...   
...                                                  ...   
12495  If you make a suspense movie it is kind of imp...   
12496  This is an embarrassing nth rehashing of the s...   
12497  What bird is that ? A maltese falcon. The only...   
12498  I made it about halfway through this movie, an...   
12499  this was pretty bad. pedestrian work or worse....   

                                                test_pos  
0      for many and many years, gaijin have visited j...  
1      Do not miss this picture that defies ages. Wit...  
2      A very credible and unsettling movie portrayin...  
3      A man and his wife are not getting along becau...  
4      Blade is a dark, gloomy, but significent vampi...  
...                                                  ...  
12495  i just wanted to say that when i was young my ...  
12496  It is by far the most definitive film on the p...  
12497  I will be honest, i rented this movie solely o...  
12498  Overall, I give this film a decent 7.6. To sta...  
12499  Two actors play rival gangsters in three films...  

[12500 rows x 4 columns]

In [11]:
pos = np.array(data_df.iloc[:2, 2])
neg = np.array(data_df.iloc[:2, 3])

In [12]:
pos

array(["If it would of had Jack Black listed as the leading actor I would of stayed away from this movie right away. It actually makes some of his movies look good compared to this movie.This movie should of been filmed as a cartoon for ages 3-8 and it would of been a lot better. It is nothing but a bunch of the stupidest skits from other movies put together to make one big mess.The movie looks like it was shot in about one day with no thought at all behind it. There's a few times where it looks like maybe there's gonna be a turning point and the movie well actually have plot to the movie or at least a storyline would develop but the stupid skits inserted just ruin the whole movie.",
       'The Quick and the Undead is, finally, the first movie to actually render its own storyline null and void. It is, essentially, one gigantic plot hole.<br /><br />Aside from that, the acting was quite bad, character motivations nonexistent or unbelievable and there wasn\'t a single character worth ha

In [13]:
neg

array(['for many and many years, gaijin have visited japan for learning martial arts, instead of acquiring any knowledge on it, gainjin have been told only nihonjin could achieve the excelent performance required to show some techniques in a "public" performance such as a movie...<br /><br />this one special movie, made by sho kosugi, not only shows all of those techniques and skills, but also teaches many and many lessons on how to achieve them, and one can verify that by seeing a LUCINDA DICKEY performing fantastic and unforgettable acting skills in NINJUTSU...<br /><br />I strongly recommend watching this movie more than thrice, because three times is not enough to seek out hints and tips given so easily by sho kosugi to those who really seek knowledge itself, the gnosis...',
       'Do not miss this picture that defies ages. With no hesitation, a masterpiece. Not only the script and the music but also choregraphy, casting,<br /><br />cut : everything contributes to the perfect achi

In [14]:
def del_urls_handles(sentence):
  
  for url in ['@', 'https://']:
    ind = 0
    while ind != -1:
      ind = sentence.find(url)
      end = sentence.find(' ', ind)
      sentence = sentence.replace(sentence[ind: end], '')
  return sentence

In [15]:
del_urls_handles(pos[0])

"If it would of had Jack Black listed as the leading actor I would of stayed away from this movie right away. It actually makes some of his movies look good compared to this movie.This movie should of been filmed as a cartoon for ages 3-8 and it would of been a lot better. It is nothing but a bunch of the stupidest skits from other movies put together to make one big mess.The movie looks like it was shot in about one day with no thought at all behind it. There's a few times where it looks like maybe there's gonna be a turning point and the movie well actually have plot to the movie or at least a storyline would develop but the stupid skits inserted just ruin the whole movie."

In [16]:
def del_punctuations(sentence):
  temp = ''
  for char in sentence:
    if char.isalnum() or char.isspace():
      temp  = temp + char
  return temp.lower()

In [17]:
del_punctuations(pos[0])

'if it would of had jack black listed as the leading actor i would of stayed away from this movie right away it actually makes some of his movies look good compared to this moviethis movie should of been filmed as a cartoon for ages 38 and it would of been a lot better it is nothing but a bunch of the stupidest skits from other movies put together to make one big messthe movie looks like it was shot in about one day with no thought at all behind it theres a few times where it looks like maybe theres gonna be a turning point and the movie well actually have plot to the movie or at least a storyline would develop but the stupid skits inserted just ruin the whole movie'

In [18]:
pr_pos = [del_punctuations(del_urls_handles(p)) for p in pos]
pr_neg = [del_punctuations(del_urls_handles(n)) for n in neg]

In [19]:
pr_pos

['if it would of had jack black listed as the leading actor i would of stayed away from this movie right away it actually makes some of his movies look good compared to this moviethis movie should of been filmed as a cartoon for ages 38 and it would of been a lot better it is nothing but a bunch of the stupidest skits from other movies put together to make one big messthe movie looks like it was shot in about one day with no thought at all behind it theres a few times where it looks like maybe theres gonna be a turning point and the movie well actually have plot to the movie or at least a storyline would develop but the stupid skits inserted just ruin the whole movie',
 'the quick and the undead is finally the first movie to actually render its own storyline null and void it is essentially one gigantic plot holebr br aside from that the acting was quite bad character motivations nonexistent or unbelievable and there wasnt a single character worth hanging our hat on the most interesting

In [20]:
pr_neg

['for many and many years gaijin have visited japan for learning martial arts instead of acquiring any knowledge on it gainjin have been told only nihonjin could achieve the excelent performance required to show some techniques in a public performance such as a moviebr br this one special movie made by sho kosugi not only shows all of those techniques and skills but also teaches many and many lessons on how to achieve them and one can verify that by seeing a lucinda dickey performing fantastic and unforgettable acting skills in ninjutsubr br i strongly recommend watching this movie more than thrice because three times is not enough to seek out hints and tips given so easily by sho kosugi to those who really seek knowledge itself the gnosis',
 'do not miss this picture that defies ages with no hesitation a masterpiece not only the script and the music but also choregraphy castingbr br cut  everything contributes to the perfect achievement now nearly 25 years ago and still amazing of mat

In [21]:
stop_words = ['i', 'am', 'and', 'was', 'that', 'the', 'you', 'he', 'she', 'we', 'they', 'were', 'of', 'too', 'them', 'are']
#These words are not complete, it is just to practice

In [22]:
def get_vocabulary(pos, neg):
  vocab, pos_words, neg_words = [], [], []
  for id, ds in enumerate([pos, neg]):
    for sentence in ds:
      for word in sentence.split():

        if word not in stop_words:
          if id == 0:
            pos_words.append(word)
          else:
            neg_words.append(word)

          vocab.append(word)

  return set(vocab), pos_words, neg_words

In [23]:
vocab, pos_words, neg_words = get_vocabulary(pr_pos, pr_neg)
len(vocab)

277

In [24]:
def frequency_dict(vocab, pos, neg):
  vocab_dict = {}
  for v in vocab:
    vocab_dict[v] = [pos.count(v), neg.count(v)]
  return vocab_dict

In [25]:
freq_dict=frequency_dict(vocab, pos_words, neg_words)

In [26]:
freq_dict

{'25': [0, 1],
 '38': [1, 0],
 'a': [15, 4],
 'about': [1, 1],
 'account': [1, 0],
 'achieve': [0, 2],
 'achievement': [0, 1],
 'acquiring': [0, 1],
 'acting': [1, 1],
 'actor': [1, 0],
 'actors': [0, 1],
 'actually': [3, 0],
 'after': [0, 1],
 'ages': [1, 1],
 'ago': [0, 1],
 'all': [1, 1],
 'also': [0, 2],
 'amazing': [0, 1],
 'an': [1, 0],
 'andbr': [0, 1],
 'any': [0, 1],
 'art': [0, 1],
 'arts': [0, 1],
 'as': [3, 1],
 'aside': [1, 0],
 'at': [2, 0],
 'available': [0, 1],
 'away': [2, 0],
 'bad': [2, 0],
 'be': [2, 0],
 'because': [0, 1],
 'been': [2, 1],
 'behind': [1, 0],
 'better': [1, 1],
 'big': [1, 0],
 'black': [1, 0],
 'br': [5, 6],
 'budget': [1, 0],
 'bunch': [2, 0],
 'burgeoning': [1, 0],
 'but': [3, 2],
 'by': [0, 3],
 'can': [0, 1],
 'cares': [1, 0],
 'cartoon': [1, 0],
 'cast': [1, 0],
 'castingbr': [0, 1],
 'character': [2, 0],
 'characters': [1, 0],
 'choregraphy': [0, 1],
 'cinematographers': [1, 0],
 'colorists': [1, 0],
 'colortiming': [1, 0],
 'compared': [1, 0

In [27]:
freq_df = pd.DataFrame(freq_dict)
freq_df.index = ['PosFreq', 'NegFreq']
freq_df = freq_df.T

In [28]:
freq_df

PosFreq  NegFreq
thrice           0        1
develop          1        0
ages             1        1
guy              1        0
but              3        2
...            ...      ...
nihonjin         0        1
no               2        1
arts             0        1
had              2        0
stupidest        1        0

[277 rows x 2 columns]

In [29]:
def extract_features(freq_df, tweet):
  x_m = [1, 0, 0]

  pos_freq = freq_df.iloc[:, 0]
  neg_freq = freq_df.iloc[:, 1]

  for t in tweet:
    if t in freq_df.index:
      pos_count, neg_count = freq_df.loc[t]
      x_m[1] += pos_count
      x_m[-1] += neg_count

  return x_m

In [30]:
fe_matrix = []
for ds in [pr_pos, pr_neg]:
  for n in ds:
    x_m = extract_features(freq_df, set(n.split()))
    fe_matrix.append(x_m)  

In [31]:
fe_matrix = np.array(fe_matrix)

In [32]:
fe_matrix

array([[  1, 169,  41],
       [  1, 217,  48],
       [  1,  82, 136],
       [  1,  51,  94]])

In [33]:
theta = np.array([0.000003, 0.00154, -0.00132])

pred = 1/(1 + np.exp(-theta.T * fe_matrix))

In [34]:
pred

array([[0.50000075, 0.5647002 , 0.4864733 ],
       [0.50000075, 0.58277609, 0.4841653 ],
       [0.50000075, 0.53152811, 0.45524014],
       [0.50000075, 0.51962491, 0.46901974]])

In [35]:
pred_classes = []
for p in pred:
  if p[1] > 0.55:
    pred_classes.append(0)
  else:
    pred_classes.append(1)

In [36]:
y = np.array([0, 0, 1, 1])
pred_classes

[0, 0, 1, 1]

In [37]:
score = 100*np.sum(y==pred_classes) / len(pred)

In [38]:
score

100.0

In [39]:
y==pred_classes

array([ True,  True,  True,  True])

In [40]:
pos_count = np.sum(freq_df.iloc[:,0])
neg_count = np.sum(freq_df.iloc[:,1])
total = len(vocab)
print(pos_count, neg_count, total)

277 187 277


In [41]:
pfreq_df = []
pfreq_df.append(freq_df.iloc[:, 0] / pos_count)
pfreq_df.append(freq_df.iloc[:, 1] / neg_count)

In [42]:
pfreq_df = pd.DataFrame(pfreq_df).T

In [43]:
pfreq_df

PosFreq   NegFreq
thrice     0.00000  0.005348
develop    0.00361  0.000000
ages       0.00361  0.005348
guy        0.00361  0.000000
but        0.01083  0.010695
...            ...       ...
nihonjin   0.00000  0.005348
no         0.00722  0.005348
arts       0.00000  0.005348
had        0.00722  0.000000
stupidest  0.00361  0.000000

[277 rows x 2 columns]

In [44]:
##### Laplacian Smoothing Frequency DataFrame ==> To remove Zeoes
ls_freq_df = []
ls_freq_df.append((freq_df.iloc[:, 0] + 1) / (pos_count + total))
ls_freq_df.append((freq_df.iloc[:, 1] + 1) / (neg_count + total))

In [45]:
ls_freq_df = pd.DataFrame(ls_freq_df).T

In [46]:
ls_freq_df

PosFreq   NegFreq
thrice     0.001805  0.004310
develop    0.003610  0.002155
ages       0.003610  0.004310
guy        0.003610  0.002155
but        0.007220  0.006466
...             ...       ...
nihonjin   0.001805  0.004310
no         0.005415  0.004310
arts       0.001805  0.004310
had        0.005415  0.002155
stupidest  0.003610  0.002155

[277 rows x 2 columns]

In [47]:
balanced_dataset_metric = pos_count / neg_count
ls_freq_df['ratio'] = balanced_dataset_metric * (ls_freq_df['PosFreq'] / ls_freq_df['NegFreq'])

In [48]:
ls_freq_df

PosFreq   NegFreq     ratio
thrice     0.001805  0.004310  0.620321
develop    0.003610  0.002155  2.481283
ages       0.003610  0.004310  1.240642
guy        0.003610  0.002155  2.481283
but        0.007220  0.006466  1.654189
...             ...       ...       ...
nihonjin   0.001805  0.004310  0.620321
no         0.005415  0.004310  1.860963
arts       0.001805  0.004310  0.620321
had        0.005415  0.002155  3.721925
stupidest  0.003610  0.002155  2.481283

[277 rows x 3 columns]

In [49]:
ls_freq_df['lambda'] = np.log(ls_freq_df['ratio'])

In [50]:
ls_freq_df

PosFreq   NegFreq     ratio    lambda
thrice     0.001805  0.004310  0.620321 -0.477518
develop    0.003610  0.002155  2.481283  0.908776
ages       0.003610  0.004310  1.240642  0.215629
guy        0.003610  0.002155  2.481283  0.908776
but        0.007220  0.006466  1.654189  0.503311
...             ...       ...       ...       ...
nihonjin   0.001805  0.004310  0.620321 -0.477518
no         0.005415  0.004310  1.860963  0.621094
arts       0.001805  0.004310  0.620321 -0.477518
had        0.005415  0.002155  3.721925  1.314241
stupidest  0.003610  0.002155  2.481283  0.908776

[277 rows x 4 columns]

In [51]:
r = np.array([[3, 4], [3, -1]])
s = np.array([[6, 0], [-4, 1]])
np.dot(r, s)

array([[ 2,  4],
       [22, -1]])

In [52]:
def forbenius_norm(x):
  squared_x = np.square(x)
  sqrt_x = np.sqrt(np.sum(squared_x))
  return sqrt_x

In [53]:
forbenius_norm(r)

5.916079783099616

In [54]:
def hash_function(value, num_buckets):
  return int(value) % num_buckets

In [55]:
hash_function(1232, 10)

2

In [56]:
def basic_hash_table(values, num_buckets):
  
  hash_table = {i: [] for i in range(num_buckets)}
  for value in values:
    hash_value = hash_function(value, num_buckets)
    hash_table[hash_value].append(value)
  return hash_table

In [57]:
values = [1, 24, 39, 4, 45]
basic_hash_table(values, 10)

{0: [],
 1: [1],
 2: [],
 3: [],
 4: [24, 4],
 5: [45],
 6: [],
 7: [],
 8: [],
 9: [39]}

In [72]:
def side_of_plane(p, v):
  dotproduct = np.dot(p, v.T)
  sign_of_dp = np.sign(dotproduct)
  return sign_of_dp

In [73]:
side_of_plane(s, r[0])

array([ 1, -1])